/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BatchEditDialog: typeof import('./src/components/BatchEditDialog/index.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ExportDialog: typeof import('./src/components/ExportDialog/index.vue')['default']
    FileUpload: typeof import('./src/components/FileUpload/index.vue')['default']
    MindmapRenderer: typeof import('./src/components/MindmapRenderer/index.vue')['default']
    MindMapViewer: typeof import('./src/components/MindMapViewer/index.vue')['default']
    ProductionMindMap: typeof import('./src/components/ProductionMindMap/index.vue')['default']
    ProgressMonitor: typeof import('./src/components/ProgressMonitor/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SessionDetail: typeof import('./src/components/SessionDetail/index.vue')['default']
    SimpleMindMap: typeof import('./src/components/SimpleMindMap/index.vue')['default']
    TcButton: typeof import('./src/components/ui/TcButton/index.vue')['default']
    TcCard: typeof import('./src/components/ui/TcCard/index.vue')['default']
    TcPageHeader: typeof import('./src/components/ui/TcPageHeader/index.vue')['default']
    TcStreamOutput: typeof import('./src/components/ui/TcStreamOutput/index.vue')['default']
    TestCaseDetailDialog: typeof import('./src/components/TestCaseDetailDialog/index.vue')['default']
    TestCaseList: typeof import('./src/components/TestCaseList/index.vue')['default']
  }
}
